@startuml

start
:User wants to add a patient;
:User runs the "add" command with Patient Hospital Id, name, preferred name, food preference, family condition and hobby;
if () then ([Required prefixes present])
  if () then ([Valid command format])
    :PatientSync checks if the input format for the respective prefix is valid;
    if () then ([Valid input format])
      :PatientSync creates Patient object;
      if () then ([Valid Patient Hospital ID])
        :PatientSync adds patient to model;
        :PatientSync displays add patient success message;
      else ([else])
        :PatientSync throws an error;
      endif
    else ([else])
      :PatientSync throws an error;
    endif
  else ([else])
    :PatientSync throws an error;
  endif
else ([else])
  :PatientSync throws an error;
endif
stop
@enduml
