@startuml

start
:User wants to add a patient;
:User runs the "add" command with id/PATIENT_HOSPITAL_ID n/NAME p/PREFERRED_NAME f/FOOD_PREFERENCE c/FAMILY_CONDITION h/HOBBY;
if () then ([Required prefixes present])
  if () then ([Valid command format])
    :PatientSync checks if the input format for the respective prefix is valid;
    if () then ([Valid input format])
      :PatientSync creates Patient object;
      if () then ([Valid Patient Hospital ID])
        :PatientSync adds patient to model;
        :PatientSync generates success message;
        :PatientSync returns success message to output;
      else ([else])
        :PatientSync throws command exception;
        :PatientSync generates error message;
        :PatientSync returns error message;
      endif
    else ([else])
      :PatientSync throws parse exception;
      :PatientSync generates error message;
      :PatientSync returns error message;
    endif
  else ([else])
    :PatientSync throws parse exception;
    :PatientSync generates error message;
    :PatientSync returns error message;
  endif
else ([else])
  :PatientSync throws parse exception;
  :PatientSync generates error message;
  :PatientSync returns error message;
endif
:PatientSync displays output message on GUI;
stop
@enduml
