@startuml
start
:User wants to edit an event for a patient;
:User runs the "edite" command with patient index, event index, new event name and new date / datetime of the event;
if () then ([else])
    :PatientSync throws an error;
else ([Valid command format])
    :PatientSync checks if the event details provided are valid;
    if () then ([else])
        :PatientSync throws an error;
    else ([Valid event details])
        :PatientSync checks if the patient index is valid;
        if () then ([else])
            :PatientSync throws an error;
        else ([Valid patient index])
            :PatientSync checks if the event index is valid;
            if () then ([else])
                :PatientSync throws an error;
            else ([Valid event index])
                :PatientSync generates the event to be edited;
                if () then ([Event already exist in the current event list])
                    :PatientSync throws an error;
                else ([else])
                    :PatientSync edits the specified event;
                    :PatientSync updates the set of events for the patient;
                    :PatientSync updates the displayed patient list;
                    :PatientSync displays edit event success message;
                endif
            endif
        endif
    endif
endif
stop
@enduml
