@startuml
start
:User wants to find a patient by tag;
:User runs the "findt" command with keyword(s);
if () then ([else])
    :PatientSync throws an error;
else ([Valid command format])
    :PatientSync searches to see whether any keyword(s) matches any existing tags from all the existing patients;
    :PatientSync updates the displayed patient list with those patients whose tag(s) matches any of the keywords;
    :PatientSync displays find patient by tag success message;
endif
stop
@enduml
